remote_theme: dieghernan/chulapa

title: Heighxomium
subtitle: Private Website

author:
  name      : Heighxomium
  avatar    : https://avatars.githubusercontent.com/u/280498728
  location  : Philippines
  links:
    - url: https://fb.me/june.12th.2019
      icon: "fab fa-facebook"
    - url: https://github.com/Heighxomium
      icon: "fab fa-github"
    - url: ph.server@pm.me
      icon: "fa fa-envelope"

navbar:
  style: "classic"
  brand:
    title: Heighxomium
    img: "https://avatars.githubusercontent.com/u/280498728"
  nav:
    - title: Home
      url: /index
    - title: Blog          # <-- ADDED
      url: /pages/index.pages/blog/          # <-- ADDED

chulapa-skin:
  skin: gitdev-dark
  vars:
    font-family-base: "Ubuntu Mono"

comments:
  provider: giscus

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      include_on_search: false
      show_comments: true
      show_date: false

# Pagination settings (ADDED)
paginate: 5
paginate_path: "/blog/page:num/"

# Miscellaneous
compress_html:
  clippings: all
  blanklines: true

plugins:
  - jekyll-github-metadata
  - jekyll-paginate
  - jekyll-include-cache
  - jekyll-sitemap

exclude:
  - LICENSE
  - Gemfile
  - vendor
  - readme

markdown: kramdown
highlighter: github
lsi: false
excerpt_separator: "\n\n"
incremental: false

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  footnote_backlink: '&uarr;'
  entity_output: as_char
  toc_levels: 2..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

sass:
  sass_dir: _sass
  style: compressed
