remote_theme: dieghernan/chulapa

title: Heighxomium
subtitle: Private Website

search:
  provider: lunr
  label: "Search"
  landing_page: "/pages/internal/search"
  show_attrib: true
  maxwords: 30

navbar:
  style: "classic"
  brand:
    title: Heighxomium
    img: "https://avatars.githubusercontent.com/u/280498728"
  nav:
  - title: Home
    url: /index
  - title: Posts
    child:
     - title: Posts
       url: /pages/index.pages/linkvertise

googlefonts:
 - url: https://fonts.googleapis.com/css2?family=Ubuntu+Mono&display=swap
chulapa-skin: 
  skin: gitdev-dark
  vars:
    font-family-base: "Ubuntu Mono"
comments:
  provider: giscus
  #https://giscus.app

collections_dir     : pages/_collections
collections:
  linkvertise:
    output: true
    permalink: /linkvertise/:name

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      include_on_search : false
      show_comments     : false
      show_date         : false
  -
    scope:
      path: "pages/_collections/_linkvertise"
    values:
      header_type       : "hero"
      header_img        : assets/images/main.001.jpeg
      show_comments     : true
      show_date         : true
      show_bottomnavs   : true

### MISCELLANEOUS ###
compress_html:
  clippings: all
  blanklines: true
plugins:
  - jekyll-github-metadata
  - jekyll-paginate
  - jekyll-include-cache
  - jekyll-sitemap
exclude:
  - LICENSE
  - Gemfile
  - vendor
  - readme
markdown: kramdown
highlighter: github
lsi: false
excerpt_separator: "\n\n"
incremental: false
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  footnote_backlink: '&uarr;'
  entity_output: as_char
  toc_levels: 2..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
sass:
  sass_dir: _sass
  style: compressed
