remote_theme: dieghernan/chulapa
title: Heighxomium
subtitle: Private Website
author:
  name      : Heighxomium
  avatar    : https://avatars.githubusercontent.com/u/280498728
  location  : Philippines
  links:
    - url: https://fb.me/june.12th.2019
      icon: "fab fa-facebook"
    - url: https://github.com/Heighxomium
      icon: "fab fa-github"
    - url: ph.server@pm.me
      icon: "fa fa-envelope"

navbar:
  style: "classic"
  brand:
    title: Heighxomium
    img: "https://avatars.githubusercontent.com/u/280498728"
  nav:
    - title: Home
      url: /index
    - title: Blog
      url: /pages/index.pages/blog

collections:
  posts:
    output: true
    permalink: /blog/:year:month:day_:title

collections_dir: collections

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      include_on_search: false
      show_comments: true
      show_date: false
      show_seo: true

- scope:
    path: ""
    type: "posts"
  values:
    header_type: "post"
    include_on_search: true
    show_date: true
    show_bottomnavs: true
    show_comments: true
    show_tags: true
    show_categories: true
    show_author: true

# Miscellaneous
comments:
  provider: giscus

chulapa-skin:
  skin: gitdev-dark
  vars:
    font-family-base: "Ubuntu Mono"

compress_html:
  clippings: all
  blanklines: true

plugins:
  - jekyll-github-metadata
  - jekyll-paginate
  - jekyll-include-cache
  - jekyll-sitemap

exclude:
  - LICENSE
  - Gemfile
  - vendor
  - readme

markdown: kramdown
highlighter: github
lsi: false
excerpt_separator: "\n\n"
incremental: false

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  footnote_backlink: '&uarr;'
  entity_output: as_char
  toc_levels: 2..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

sass:
  sass_dir: _sass
  style: compressed
